# Pull the base image
FROM node:lts-alpine as builder

# Set the working direction
WORKDIR /app

# Install dependencies
COPY package.json .
RUN npm i -g @angular/cli
RUN npm i

# Copy other files to container
COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
