# Pull the base image
FROM node:lts-alpine

# Set the working direction
WORKDIR /app

# Install dependencies
COPY package.json .
RUN yarn

# Copy other files to container
COPY . .

# start app
CMD ["yarn", "run", "dev"]
